/**
 * Example provider recipe (TypeScript).
 *
 * Drop a copy at `.mulch/recipes/<name>.ts` and run `ml setup <name>`.
 * Mulch's resolver prefers filesystem recipes over npm and built-in, so you
 * can also use this shape to override a built-in (e.g. `claude.ts`).
 */
import { existsSync } from "node:fs";
import { mkdir, readFile, unlink, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";

interface RecipeResult {
	success: boolean;
	message: string;
}

const CONFIG_REL_PATH = ".internal-ide/mulch.config";

const CONFIG_CONTENTS = `# Auto-generated by mulch setup. Do not edit by hand.
on_session_start: ml prime
on_pre_compact: ml prime
`;

function configPath(cwd: string): string {
	return join(cwd, CONFIG_REL_PATH);
}

export default {
	async install(cwd: string): Promise<RecipeResult> {
		const path = configPath(cwd);
		if (existsSync(path)) {
			const existing = await readFile(path, "utf-8");
			if (existing === CONFIG_CONTENTS) {
				return { success: true, message: "Internal-IDE integration already installed." };
			}
		}
		await mkdir(dirname(path), { recursive: true });
		await writeFile(path, CONFIG_CONTENTS, "utf-8");
		return { success: true, message: `Installed Internal-IDE config at ${CONFIG_REL_PATH}.` };
	},

	async check(cwd: string): Promise<RecipeResult> {
		const path = configPath(cwd);
		if (!existsSync(path)) {
			return { success: false, message: "Internal-IDE config not found." };
		}
		const content = await readFile(path, "utf-8");
		if (content !== CONFIG_CONTENTS) {
			return { success: false, message: "Internal-IDE config exists but has been modified." };
		}
		return { success: true, message: "Internal-IDE config is installed and correct." };
	},

	async remove(cwd: string): Promise<RecipeResult> {
		const path = configPath(cwd);
		if (!existsSync(path)) {
			return { success: true, message: "Internal-IDE config not found; nothing to remove." };
		}
		await unlink(path);
		return { success: true, message: `Removed ${CONFIG_REL_PATH}.` };
	},
};
