#!/bin/sh
# Example provider recipe (shell).
#
# Drop a copy at .mulch/recipes/<name>.sh, chmod +x it, and run `ml setup <name>`.
# Mulch invokes this script as: <script> install|check|remove
# with cwd = project root and MULCH_RECIPE_NAME / MULCH_RECIPE_ACTION in env.
#
# Stdout becomes the success message. Non-zero exit signals failure;
# stderr is surfaced to the user.

set -e

CONFIG_FILE=".legacy-bot/mulch.txt"

case "$1" in
	install)
		mkdir -p "$(dirname "$CONFIG_FILE")"
		cat > "$CONFIG_FILE" <<EOF
# Auto-generated by mulch setup. Do not edit by hand.
ml prime
EOF
		echo "Installed Legacy-Bot integration at $CONFIG_FILE."
		;;
	check)
		if [ -f "$CONFIG_FILE" ]; then
			echo "Legacy-Bot integration is installed."
		else
			echo "Legacy-Bot config not found at $CONFIG_FILE." 1>&2
			exit 1
		fi
		;;
	remove)
		if [ -f "$CONFIG_FILE" ]; then
			rm -f "$CONFIG_FILE"
			echo "Removed $CONFIG_FILE."
		else
			echo "Legacy-Bot config not found; nothing to remove."
		fi
		;;
	*)
		echo "Unknown action: $1 (expected install|check|remove)" 1>&2
		exit 2
		;;
esac
